project:
  type: website
  resources: 
    - "site/*"
execute:
  freeze: auto
website:
  favicon: site/logo_black_small.png # https://quarto.org/docs/websites/website-tools.html#favicon
  twitter-card: true # https://quarto.org/docs/websites/website-tools.html#twitter-cards
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  title: "Arcadia Science"
  navbar:
    title: false
    left:
      - text: "{{< iconify qlementine-icons:version-control-16 >}}"
        menu:
          - text: latest
            href: index.ipynb
      - text: Residue prediction dependencies in ESM2
        href: index.ipynb
    right:
      - text: FAQ
        href: faq.qmd
    tools:
      - icon: twitter-x
        href: https://twitter.com/arcadiascience
      - icon: github
        href: https://github.com/Arcadia-Science/notebook-pub-template
    logo: site/logo_static.png
    logo-href: https://www.arcadiascience.com/
    background: white
    search: true
  page-footer:
    background: "#484B50"
    border: false
    left: |
      [![](site/logo_white_small.png){fig-alt="Arcadia-Science" width=65px}](https://www.arcadiascience.com/)
      Copyright 2024, Arcadia Science
    right:
      - icon: twitter-x
        href: https://twitter.com/arcadiascience
      - icon: github
        href: https://github.com/Arcadia-Science/notebook-pub-template
format:
  html:
    include-in-header:
      file: site/logo-animation.html
    css: site/styles.css
    page-layout: article
    title-block-banner: true
    toc: true
comments:
  giscus:
    repo: Arcadia-Science/notebook-pub-template
    input-position: top
