project:
  type: website
  resources: 
    - "assets/*"
execute:
  freeze: auto
website:
  favicon: assets/logo_white.png # https://quarto.org/docs/websites/website-tools.html#favicon
  twitter-card: true # https://quarto.org/docs/websites/website-tools.html#twitter-cards
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    title: false
    left:
      - text: "{{< iconify qlementine-icons:version-control-16 >}}"
        menu:
          - text: latest
            href: index.ipynb
      - text: "{{< var pub.title >}}"
        href: index.ipynb
    right:
      - text: FAQ
        href: FAQ.qmd
      - text: Contributing
        href: CONTRIBUTING.qmd
    tools:
      - icon: twitter-x
        href: https://twitter.com/arcadiascience
      - icon: github
        href: https://github.com/{{< var pub.repo >}}
    logo: assets/logo_text.png
    logo-href: https://www.arcadiascience.com/
    background: white
    search: true
  page-footer:
    background: "#484B50"
    border: false
    left: |
      [![](assets/logo_white.png){fig-alt="Arcadia-Science" width=65px}](https://www.arcadiascience.com/)
      Copyright 2024, Arcadia Science
    right:
      - icon: twitter-x
        href: https://twitter.com/arcadiascience
      - icon: github
        href: https://github.com/{{< var pub.repo >}}
format:
  html:
    include-in-header:
      file: assets/logo-animation.html
    css: assets/styles.css
    page-layout: article
    title-block-banner: true
    toc: true
comments:
  giscus:
    repo: "{{< var pub.repo >}}"
    input-position: top
